# Generated by Django 5.1.5 on 2025-01-22 17:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('valor', models.PositiveIntegerField(default=0, help_text='Valor de la actividad (0-500).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('multiplicador', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Multiplicador')),
                ('np_is', models.BooleanField(default=False)),
                ('nivel_pertinencia', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nivel de pertinencia')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividad',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'db_table': 'asignatura',
            },
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('valor', models.PositiveIntegerField(default=0, help_text='Valor del criterio (0-500).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
            ],
            options={
                'verbose_name': 'Criterio',
                'verbose_name_plural': 'Criterios',
                'db_table': 'criterio',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=250, verbose_name='Nombre')),
                ('valorMaximo', models.PositiveIntegerField(default=0, help_text='Valor máximo del nivel de desempeño (0-499).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(499)], verbose_name='Valor máximo')),
                ('valorMinimo', models.PositiveIntegerField(default=0, help_text='Valor mínimo del nivel de desempeño (1-500).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Valor mínimo')),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
                'db_table': 'Nivel',
            },
        ),
        migrations.CreateModel(
            name='AsignaturaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.asignatura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='user',
            field=models.ManyToManyField(related_name='asignaturas', through='public.AsignaturaUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('descripcion', models.CharField(max_length=30, null=True, verbose_name='Descripción')),
                ('anotacion', models.CharField(max_length=100, null=True, verbose_name='Anotación')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='public.actividad')),
                ('asignaturaUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.asignaturauser')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'calificacion',
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='criterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='public.criterio'),
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('valor', models.PositiveIntegerField(default=0, help_text='Valor de la dimensión (0-500).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensiones', to='public.asignatura')),
            ],
            options={
                'verbose_name': 'Dimensión',
                'verbose_name_plural': 'Dimensiones',
                'db_table': 'dimension',
            },
        ),
        migrations.AddField(
            model_name='criterio',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='public.dimension'),
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('nit', models.PositiveIntegerField(unique=True, verbose_name='NIT')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instituciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
                'db_table': 'institucion',
            },
        ),
        migrations.CreateModel(
            name='Monitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Predeterminado', max_length=30, verbose_name='Nombre')),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Monitoreos', to='public.asignatura')),
            ],
            options={
                'verbose_name': 'Monitoreo',
                'verbose_name_plural': 'Monitoreos',
                'db_table': 'Monitoreo',
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='monitoreo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='public.monitoreo'),
        ),
        migrations.CreateModel(
            name='NivelCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anotacion', models.CharField(default=' ', max_length=250, verbose_name='Anotación')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nivel_criterios', to='public.criterio')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nivel_criterios', to='public.nivel')),
            ],
            options={
                'verbose_name': 'NivelCriterio',
                'verbose_name_plural': 'NivelCriterios',
                'db_table': 'nivel_criterio',
            },
        ),
        migrations.AddField(
            model_name='nivel',
            name='criterios',
            field=models.ManyToManyField(related_name='niveles', through='public.NivelCriterio', to='public.criterio'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='images/users/user.png', upload_to='images/users/', verbose_name='Imagen de perfil')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('location', models.CharField(blank=True, max_length=150, null=True, verbose_name='Localidad')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True, verbose_name='Sexo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='public.institucion')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'db_table': 'programa',
            },
        ),
        migrations.AddField(
            model_name='asignatura',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='public.programa'),
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anotacion', models.CharField(default='', max_length=600, verbose_name='Anotación')),
                ('imagen', models.ImageField(default='images/rubricas/imgEmpty.png', upload_to='images/rubricas/', verbose_name='Imagen de rúbrica')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubricas', to='public.asignatura')),
            ],
            options={
                'verbose_name': 'Rúbrica',
                'verbose_name_plural': 'Rúbricas',
                'db_table': 'rubrica',
            },
        ),
        migrations.AddField(
            model_name='nivel',
            name='rubrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='public.rubrica'),
        ),
    ]
