# Generated by Django 5.1.5 on 2025-02-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_remove_institucion_nit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubrica',
            options={'verbose_name': 'rubrica', 'verbose_name_plural': 'rubricas'},
        ),
    ]
